-- H2 本地文件数据库初始化脚本。F1 在此基础上补充业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- =====================================================================
-- 连锁洗车 · 门店侧底账
-- 公共审计列约定（所有业务表）：
--   request_no   请求号（每次写入请求唯一，可外部传入幂等）
--   operator     操作人
--   biz_time     业务时间（业务发生时间，区别于系统 create_time）
--   data_version 数据版本（乐观锁，每次更新 +1）
--   deleted      删除标记（0 正常 / 1 已删，只做标记不物理删除）
-- 日志型表（流转留痕 / 反向记录 / 扣次记录）为 append-only，无 deleted/version。
-- =====================================================================

-- 工位基础信息
CREATE TABLE IF NOT EXISTS t_wash_bay (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code VARCHAR(32) NOT NULL,
    bay_code VARCHAR(32) NOT NULL,
    bay_name VARCHAR(64) NOT NULL,
    bay_type VARCHAR(16) NOT NULL DEFAULT 'STANDARD',
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    data_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wash_bay UNIQUE (store_code, bay_code)
);

-- 会员卡（按次数扣减）
CREATE TABLE IF NOT EXISTS t_member_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_no VARCHAR(32) NOT NULL,
    store_code VARCHAR(32) NOT NULL,
    holder_name VARCHAR(64),
    holder_phone VARCHAR(32),
    total_times INT NOT NULL DEFAULT 0,
    remaining_times INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    data_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_member_card UNIQUE (card_no)
);

-- 洗车工单主表
CREATE TABLE IF NOT EXISTS t_wash_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL,
    store_code VARCHAR(32) NOT NULL,
    bay_id BIGINT,
    bay_code VARCHAR(32),
    card_no VARCHAR(32),
    plate_no VARCHAR(16),
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    data_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wash_order UNIQUE (order_no)
);
CREATE INDEX IF NOT EXISTS idx_wash_order_card ON t_wash_order (card_no);
CREATE INDEX IF NOT EXISTS idx_wash_order_status ON t_wash_order (status);
CREATE INDEX IF NOT EXISTS idx_wash_order_store ON t_wash_order (store_code, status);

-- 洗车工单明细（与主表同生共死）
CREATE TABLE IF NOT EXISTS t_wash_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL,
    item_name VARCHAR(64) NOT NULL,
    item_type VARCHAR(16) NOT NULL DEFAULT 'WASH',
    qty INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    data_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_wash_order_item_order ON t_wash_order_item (order_no);

-- 状态流转留痕（含被拒绝的越级迁移，append-only）
CREATE TABLE IF NOT EXISTS t_wash_order_flow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL,
    action VARCHAR(16) NOT NULL,
    from_status VARCHAR(16),
    to_status VARCHAR(16) NOT NULL,
    accepted CHAR(1) NOT NULL DEFAULT 'Y',
    reject_reason VARCHAR(255),
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_wash_order_flow_order ON t_wash_order_flow (order_no);

-- 作废反向记录（作废不删不改原记录，新增一条反向记录，append-only）
CREATE TABLE IF NOT EXISTS t_wash_order_reversal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reversal_no VARCHAR(40) NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    reversed_status VARCHAR(16) NOT NULL,
    compensate_card CHAR(1) NOT NULL DEFAULT 'N',
    reason VARCHAR(255),
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wash_order_reversal UNIQUE (reversal_no)
);
CREATE INDEX IF NOT EXISTS idx_wash_order_reversal_order ON t_wash_order_reversal (order_no);

-- 会员卡扣次/回补记录（append-only）
CREATE TABLE IF NOT EXISTS t_card_deduct_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_no VARCHAR(32) NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    change_type VARCHAR(16) NOT NULL,
    change_times INT NOT NULL,
    balance_after INT NOT NULL,
    request_no VARCHAR(64) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    biz_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_card_deduct_log_card ON t_card_deduct_log (card_no);
CREATE INDEX IF NOT EXISTS idx_card_deduct_log_order ON t_card_deduct_log (order_no);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('carwash-1', '连锁洗车门店底账：工位/会员卡/工单主明细/流转留痕/反向记录/扣次记录');
